### ISSUE TITLE
change delivery address of packages in dashboard

### ISSUE THREAD

**Issue by prabinspkt** [Driven-SP/driven#16]
If the packages have not been delivered, we should let users change
the delivery address from the dashboard.
This change needs to be relayed to vendors. Needs some thought!

Address information does not exist in package document, so add this
info when implementing.

**Comment by prabinspkt** [comment]
One way this can be done is updating the information in Firestore, and when vendors try to update the status of packages, they verify that the address is same each time. This means if the package has already left for final destination, vendor will only change the status to DELIVERED without verifying the address. This is simple approach with one limitation.

**Comment by kaushik530411** [comment]
Sounds like a good approach to me. For the UI side I was wondering if it will be a good idea to add some sorting/classifying mechanism. Like displaying all the Mails based on Address (which address it is being delivered to) and Vendor. Let me know what you think.
